apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs_app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: docs_app
  template:
    metadata:
      labels:
        app: docs_app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - docs_app
            topologyKey: kubernetes.io/hostname
      containers:
        - name: flask-k8s
          image:  eu.gcr.io/${PROJECT}/flask
          imagePullPolicy: Always
          ports:
            - name: flask-port
              containerPort: 5000
          env:
            - name: DOCS_BUCKET
              value: $DOCS_BUCKET
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
      nodeSelector:
        cloud.google.com/gke-nodepool: ${BASE_NODE_POOL}
        iam.gke.io/gke-metadata-server-enabled: "true"