apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "{{ params.name }}"
spec:
  type: Python
  mode: cluster
  pythonVersion: "3"
  sparkVersion: "3.1.2"
  imagePullPolicy: {{ params.imagePullPolicy | default('Never') }}
  image: "{{ params.image }}"
  restartPolicy:
    type: {{ params.restartPolicy | default('Never') }}
  mainApplicationFile: "{{ params.mainApplicationFile }}"
  hadoopConf:
  "fs.gs.project.id": "{{ params.project }}"
  "google.cloud.auth.service.account.enable": "true"
  "google.cloud.auth.service.account.json.keyfile": "/mnt/secrets/key.json"
  "fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
  "fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
{% if params.volumes is defined or (params.gitsync is defined and params.gitsync) %}
  volumes:
  {% if params.volumes is defined %}
    {% for volume in params.volumes %}
    - name: {{ volume.name }}
      {% if volume.type == 'secret' %}
      secret:
        secretName: {{ volume.reference }}
      {% elif volume.type == 'configMap' %}
      configMap:
        name: {{ volume.reference }}
      {% elif volume.type == 'emptyDir' %}
      emptyDir: {}
      {% endif %}
    {% endfor %}
    {% endif %}
    {% if params.gitsync is defined and params.gitsync %}
    - name: code
      emptyDir: {}
    {% endif %}
  {% endif %}
  # nodeSelector:
  #   iam.gke.io/gke-metadata-server-enabled: "true"
  #   {% if params.nodeSelector is defined %}
  #   cloud.google.com/gke-nodepool: {{ params.nodeSelector }}
  #   {% endif %}
  driver:
    cores: 1
    coreLimit: "1200m"
    coreRequest: 100m
    memory: "512m"
    secrets:
      - name: "gcsfs-creds"
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
      {% if params.envFrom is defined  %}
    envFrom:
    {% for envFrom in params.envFrom %}
    - {% if envFrom.type == 'configMapRef' %}
        configMapRef:
            name: {{ envFrom.name }}
        {% else %}
        secretRef:
            name: {{ envFrom.name }}
        {% endif %}
    {% endfor %}
    {% endif %}
    {% if params.env is defined %}
    env:
    {% for key, value in params.env.items() %}
    - name: {{ key }}
      value: {{ value }}
    {% endfor %}
    {% endif %}
    labels:
      version: 3.1.2
      metrics-exposed: "true"
    serviceAccount:  {{ params.imagePullPolicy | default('default') }}
      {% if params.volumes is defined or (params.gitsync is defined and params.gitsync) %}
    volumeMounts:
    {% if params.volumes is defined %}
    {% for volume in params.volumes %}
    - name: {{ volume.name }}
        mountPath: {{ volume.mountPath }}
        {% if volume.subPath is defined %}
        subPath: {{ volume.subPath }}
        {% endif %}
    {% endfor %}
    {% endif %}
    {% if params.gitsync is defined and params.gitsync %}
    - name: code
        mountPath: /git
    {% endif %}
    {% endif %}
    {% if params.gitsync is defined and params.gitsync %}
    initContainers:
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.6.2
        imagePullPolicy: Always
        securityContext:
          runAsUser: 65533
        env:
          - name: GIT_SYNC_ONE_TIME
            value: "true"
        envFrom:
          - configMapRef:
              name: git-env
        resources: {}
        volumeMounts:
          - name: code
            mountPath: /git
    {% endif %}
  executor:
    cores: 1
    coreRequest: 100m
    instances: {{ params.instances }}
    memory: "512m"
      {% if params.envFrom is defined  %}
    envFrom:
    {% for envFrom in params.envFrom %}
    - {% if envFrom.type == 'configMapRef' %}
        configMapRef:
            name: {{ envFrom.name }}
        {% else %}
        secretRef:
            name: {{ envFrom.name }}
        {% endif %}
    {% endfor %}
    {% endif %}
    {% if params.env is defined %}
    env:
    {% for key, value in params.env.items() %}
    - name: {{ key }}
      value: {{ value }}
    {% endfor %}
    {% endif %}
    secrets:
      - name: "gcsfs-creds"
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
    labels:
      version: 3.1.2
      metrics-exposed: "true"
      {% if params.volumes is defined or (params.gitsync is defined and params.gitsync) %}
    volumeMounts:
    {% if params.volumes is defined %}
    {% for volume in params.volumes %}
    - name: {{ volume.name }}
        mountPath: {{ volume.mountPath }}
        {% if volume.subPath is defined %}
        subPath: {{ volume.subPath }}
        {% endif %}
    {% endfor %}
    {% endif %}
    {% if params.gitsync is defined and params.gitsync %}
    - name: code
        mountPath: /git
    {% endif %}
    {% endif %}
    {% if params.gitsync is defined and params.gitsync %}
    initContainers:
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.6.2
        imagePullPolicy: Always
        securityContext:
          runAsUser: 65533
        env:
          - name: GIT_SYNC_ONE_TIME
            value: "true"
        envFrom:
          - configMapRef:
              name: git-env
        resources: {}
        volumeMounts:
          - name: code
            mountPath: /git
    {% endif %}
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.11.0.jar"
      port: 8090
