[tool.poetry]
name = "grandiose"
version = "0.1.0"
description = ""
authors = ["Lestrang1991 <liftingthedata@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dbt-bigquery = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
