apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  labels:
    app: postgresql
  annotations:
    reloader.stakater.com/match: "true"
data:
  PGDATA: "/var/lib/postgresql/data/"
  POSTGRESQL_PORT_NUMBER: "5432"
  POSTGRESQL_VOLUME_DIR: "/data"
  POSTGRES_USER: "postgres"
  POSTGRESQL_ENABLE_LDAP: "no"
  POSTGRESQL_ENABLE_TLS: "no"
  POSTGRESQL_LOG_HOSTNAME: "false"
  POSTGRESQL_LOG_CONNECTIONS: "false"
  POSTGRESQL_LOG_DISCONNECTIONS: "false"
  POSTGRESQL_PGAUDIT_LOG_CATALOG: "off"
  POSTGRESQL_CLIENT_MIN_MESSAGES: "error"
  POSTGRESQL_SHARED_PRELOAD_LIBRARIES: "pgaudit"
