apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  annotations:
    reloader.stakater.com/match: "true"
stringData:
  AIRFLOW_DB: ${AIRFLOW_DB}
  AIRFLOW_DB_USER: ${AIRFLOW_DB_USER}
  AIRFLOW_DB_PASSWORD: ${AIRFLOW_DB_PASSWORD}
  MLFLOW_DB: ${MLFLOW_DB}
  MLFLOW_DB_USER: ${MLFLOW_DB_USER}
  MLFLOW_DB_PASSWORD: ${MLFLOW_DB_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}