config_version: 3
datasources:
  NyTaxiData:
    module_name: great_expectations.datasource
    class_name: Datasource
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: SparkDFExecutionEngine
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
      default_inferred_data_connector_name:
        class_name: InferredAssetGCSDataConnector
        project: ${PROJECT}
        bucket_or_name: ${STAGING_BUCKET}
        # prefix: 
        default_regex:
          pattern: (.*)\.parquet
          # group_names:
          #     - 
stores:
  expectations_GCS_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleGCSStoreBackend
      project: ${PROJECT}
      bucket: ${DOCS_BUCKET}
      prefix: great_expectations/expectations

  validations_GCS_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleGCSStoreBackend
      project: ${PROJECT}
      bucket: ${DOCS_BUCKET}
      prefix: great_expectations/validations
  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_GCS_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleGCSStoreBackend
      project: ${PROJECT}
      bucket: ${DOCS_BUCKET}
      prefix: great_expectations/checkpoints
expectations_store_name: expectations_GCS_store
validations_store_name: validations_GCS_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_GCS_store
data_docs_sites:
  NyTaxiDocs:
    class_name: SiteBuilder
    show_how_to_buttons: false
    store_backend:
      class_name: TupleGCSStoreBackend
      project: ${PROJECT}
      bucket: ${DOCS_BUCKET}
      prefix: great_expectations/docs
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
# validation_operators:
#   action_list_operator:
#     class_name: ActionListValidationOperator
#     action_list:
#       - name: store_validation_result
#         action:
#           class_name: StoreValidationResultAction
#       - name: store_evaluation_params
#         action:
#           class_name: StoreEvaluationParametersAction
#       - name: update_data_docs
#         action:
#           class_name: UpdateDataDocsAction
# anonymous_usage_statistics: false

