apiVersion: v1
kind: Service
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: airflow
  ports:
    - name: task-logs
      port: 8793
      targetPort: 8793
