{
 "title": "Airflow Spark Metrics",
 "tags": [ "SparkApplications" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Airflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of DAGs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "af_agg_dagbag_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Currently Running Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Instances Successes & Failures",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_operator_successes{operator=\"KubernetesJobOperator\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "airflow_operator_failures{operator=\"KubernetesJobOperator\"}",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Failed Runs Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(airflow_dagrun_failed_count)",
     "legendFormat": "Failed Dag Runs Count"
    }
   ]
  },
  {
   "title": "Kubernetes Pods Created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_task_instance_created_KubernetesJobOperator",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Run Duration in Minutes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dagrun_duration_sum{dag_id=\"batch-dag\"}/60",
     "legendFormat": "Batch Dag"
    },
    {
     "expr": "airflow_dagrun_duration_sum{dag_id=\"full-refresh\"}/60",
     "legendFormat": "Full Refresh/Initial Load Dag"
    },
    {
     "expr": "airflow_dagrun_duration_sum{dag_id=\"lambda_integration_test\"}/60",
     "legendFormat": "Lambda Integration Test Dag"
    }
   ]
  },
  {
   "title": "Task Run Duration in Minutes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_task_duration_sum/60", "legendFormat": "{{dag_id}}-{{task_id}}" }
   ]
  },
  {
   "title": "Scheduler Heartbeat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(af_agg_scheduler_heartbeat[10m])*60",
     "legendFormat": "Heartbeats per Minute"
    }
   ]
  },
  {
   "title": "Executor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "af_agg_executor_open_slots", "legendFormat": "Open Slots" },
    { "expr": "af_agg_executor_queued_tasks", "legendFormat": "Queued Tasks" },
    { "expr": "af_agg_executor_running_tasks", "legendFormat": "Running Tasks" }
   ]
  },
  {
   "title": "Scheduler Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_executable",
     "legendFormat": "Executable"
    },
    {
     "expr": "airflow_scheduler_tasks_pending",
     "legendFormat": "Pending"
    },
    {
     "expr": "airflow_scheduler_tasks_running",
     "legendFormat": "Running"
    },
    {
     "expr": "airflow_scheduler_tasks_starving",
     "legendFormat": "Starving"
    },
    {
     "expr": "airflow_scheduler_tasks_killed_externally",
     "legendFormat": "Killed Externally"
    },
    {
     "expr": "airflow_scheduler_tasks_without_dagrun",
     "legendFormat": "Without DagRun"
    }
   ]
  },
  {
   "title": "Spark Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor Success %",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "spark_app_executor_success_count/(spark_app_executor_success_count+spark_app_executor_failure_count)*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Success Duration",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 7, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(spark_app_failure_execution_time_microseconds_sum)/spark_app_success_execution_time_microseconds_count/60000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Spark Jobs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 13, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "spark_app_failure_count+spark_app_success_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Running Spark Jobs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "spark_app_running_count", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Jobs Run Time (Minutes)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 13, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "spark_app_failure_count", "legendFormat": "Failed Jobs" },
      { "expr": "spark_app_success_count", "legendFormat": "Successful Jobs" }
     ]
    },
    {
     "title": "Failed vs Succeeded Spark Jobs Run Time in Minutes",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "spark_app_failure_execution_time_microseconds_sum/60000000",
       "legendFormat": "Failed Jobs"
      },
      {
       "expr": "spark_app_success_execution_time_microseconds_sum/60000000",
       "legendFormat": "Successful Jobs"
      }
     ]
    }
   ]
  }
 ]
}