apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: prometheus.default.svc.cluster.local:9090
    # - name: Google Cloud Monitoring
    #   # https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/
    #   type: stackdriver
    #   access: proxy
    #   jsonData:
    #     authenticationType: gce

