apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-secret
  annotations:
    reloader.stakater.com/match: "true"
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
  GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}