apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: grafana
    svc: external-lb
spec:
  selector:
    matchLabels:
      app: grafana
      svc: external-lb
  template:
    metadata:
      labels:
        app: grafana
        svc: external-lb
    spec:
      securityContext:
            runAsUser: 472
            runAsGroup: 472
            fsGroup: 472
      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: GF_SECURITY_ADMIN_PASSWORD
          ports:
            - name: grafana-port
              containerPort: 3000
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/
              readOnly: true
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards/
              readOnly: true
            - name: kube-state-dashboard
              mountPath: /opt/grafana/dashboards/kube
              readOnly: false
            - name: airflow-spark-dashboard
              mountPath: /opt/grafana/dashboards/airflow_spark
              readOnly: false
            - mountPath: /var/lib/grafana
              name: grafana-pv
          resources:
            {}
      nodeSelector:
        cloud.google.com/gke-nodepool: ${BASE_NODE_POOL}
        iam.gke.io/gke-metadata-server-enabled: "true"
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
        - name: grafana-dashboards
          configMap:
              defaultMode: 420
              name: grafana-dashboards
        - name: airflow-spark-dashboard
          configMap:
              defaultMode: 420
              name: airflow-spark-dashboard
        - name: kube-state-dashboard
          configMap:
              defaultMode: 420
              name: kube-state-dashboard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi