apiVersion: v1
kind: ConfigMap
metadata:
  name: bq-bi-dashboard
data:
  bq-bi-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "title": "Panel Title",
          "type": "timeseries"
        }
      ],
      "schemaVersion": 37,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "selected": true,
              "text": [
                "1"
              ],
              "value": [
                "1"
              ]
            },
            "datasource": {
              "type": "grafana-bigquery-datasource",
              "uid": "P4eaJP04z"
            },
            "definition": "",
            "hide": 0,
            "includeAll": true,
            "label": "Month",
            "multi": true,
            "name": "month",
            "options": [],
            "query": {
              "dataset": "models_historical",
              "editorMode": "code",
              "format": 1,
              "location": "europe-west1",
              "project": "stellarismusv2",
              "rawQuery": true,
              "rawSql": "SELECT DISTINCT month FROM `stellarismusv2.models_historical.dbt__bi__yellow_m2m` \r\nOrder by 1",
              "sql": {
                "columns": [
                  {
                    "parameters": [
                      {
                        "name": "month",
                        "type": "functionParameter"
                      }
                    ],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              },
              "table": "dbt__bi__yellow_m2m"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "current": {
              "selected": true,
              "text": [
                "2010"
              ],
              "value": [
                "2010"
              ]
            },
            "datasource": {
              "type": "grafana-bigquery-datasource",
              "uid": "P4eaJP04z"
            },
            "definition": "",
            "hide": 0,
            "includeAll": true,
            "label": "Year",
            "multi": true,
            "name": "year",
            "options": [],
            "query": {
              "dataset": "models_historical",
              "editorMode": "code",
              "format": 1,
              "location": "europe-west1",
              "project": "stellarismusv2",
              "rawQuery": true,
              "rawSql": "SELECT DISTINCT year FROM `stellarismusv2.models_historical.dbt__bi__yellow_m2m` \r\nOrder by 1",
              "sql": {
                "columns": [
                  {
                    "parameters": [
                      {
                        "name": "month",
                        "type": "functionParameter"
                      }
                    ],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              },
              "table": "dbt__bi__yellow_m2m"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "current": {
              "selected": true,
              "text": [
                "Creative Mobile Technologies, LLC"
              ],
              "value": [
                "Creative Mobile Technologies, LLC"
              ]
            },
            "datasource": {
              "type": "grafana-bigquery-datasource",
              "uid": "P4eaJP04z"
            },
            "definition": "",
            "hide": 0,
            "includeAll": true,
            "label": "Vendor",
            "multi": true,
            "name": "vendor",
            "options": [],
            "query": {
              "dataset": "models_historical",
              "editorMode": "code",
              "format": 1,
              "location": "europe-west1",
              "project": "stellarismusv2",
              "rawQuery": true,
              "rawSql": "SELECT DISTINCT vendors FROM `stellarismusv2.models_historical.dbt__bi__yellow_m2m` \r\nOrder by 1",
              "sql": {
                "columns": [
                  {
                    "parameters": [
                      {
                        "name": "month",
                        "type": "functionParameter"
                      }
                    ],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              },
              "table": "dbt__bi__yellow_m2m"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "current": {
              "selected": false,
              "text": "All",
              "value": "$__all"
            },
            "datasource": {
              "type": "grafana-bigquery-datasource",
              "uid": "P4eaJP04z"
            },
            "definition": "",
            "hide": 0,
            "includeAll": true,
            "label": "Borough",
            "multi": true,
            "name": "borough",
            "options": [],
            "query": {
              "dataset": "models_historical",
              "editorMode": "code",
              "format": 1,
              "location": "europe-west1",
              "project": "stellarismusv2",
              "rawQuery": true,
              "rawSql": "SELECT DISTINCT pickup_borough FROM `stellarismusv2.models_historical.dbt__bi__yellow_m2m` \r\nOrder by 1",
              "sql": {
                "columns": [
                  {
                    "parameters": [
                      {
                        "name": "month",
                        "type": "functionParameter"
                      }
                    ],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              },
              "table": "dbt__bi__yellow_m2m"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "current": {
              "selected": false,
              "text": "All",
              "value": "$__all"
            },
            "datasource": {
              "type": "grafana-bigquery-datasource",
              "uid": "P4eaJP04z"
            },
            "definition": "",
            "hide": 0,
            "includeAll": true,
            "label": "Zone",
            "multi": true,
            "name": "zone",
            "options": [],
            "query": {
              "dataset": "models_historical",
              "editorMode": "code",
              "format": 1,
              "location": "europe-west1",
              "project": "stellarismusv2",
              "rawQuery": true,
              "rawSql": "SELECT DISTINCT pickup_zone FROM `stellarismusv2.models_historical.dbt__bi__yellow_m2m` \r\nOrder by 1",
              "sql": {
                "columns": [
                  {
                    "parameters": [
                      {
                        "name": "month",
                        "type": "functionParameter"
                      }
                    ],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              },
              "table": "dbt__bi__yellow_m2m"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "New dashboard",
      "version": 0,
      "weekStart": ""
    }