apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  annotations:
    reloader.stakater.com/match: "true"
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.default.svc.cluster.local:9090
      - name: BigQuery DS
        type: grafana-bigquery-datasource
        editable: true
        enabled: true
        defaultProject: ${PROJECT}
        jsonData:
          authenticationType: gce