apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: GF_SECURITY_ADMIN_PASSWORD
          ports:
            - name: grafana-port
              containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/
              readOnly: true
          resources:
            {}
            # - name: grafana-dashboards
            #   mountPath: /etc/grafana/provisioning/dashboards/
            #   readOnly: true
            # - name: grafana-data-drift-dashboard
            #   mountPath: /opt/grafana/dashboards/
            #   readOnly: false
          # resources:
          #   requests:
          #     memory: "32Mi"
          #     cpu: "125m"
          #   limits:
          #     memory: "64Mi"
          #     cpu: "250m"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${BASE_NODE_POOL}
        iam.gke.io/gke-metadata-server-enabled: "true"
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
        # - name: grafana-dashboards
        #   configMap:
        #       defaultMode: 420
        #       name: grafana-dashboards
        # - name: grafana-data-drift-dashboard
        #   configMap:
        #       defaultMode: 420
        #       name: grafana-data-drift-dashboard
