apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-env
data:
  # GCP INFRA
  YELLOW_TRIAGE: "${TRIAGE_DATASET}.${YELLOW_TRIAGE_TABLE}"
  YELLOW_STAGING: "${STAGING_DATASET}.${YELLOW_STAGING_TABLE}"
  YELLOW_SUMMARY: "${HISTORICAL_DATASET}.${YELLOW_SUMMARY_TABLE}"
