apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-env
data:
  # GCP INFRA
  YELLOW_TRIAGE: "${TRIAGE_DATASET}.${YELLOW_TRIAGE_TABLE}"
  YELLOW_STAGING: "${STAGING_DATASET}.${YELLOW_STAGING_TABLE}"
  YELLOW_SUMMARY: "${HISTORICAL_DATASET}.${YELLOW_SUMMARY_TABLE}"
  YELLOW_HIST_CLUSTERING_COL: "pickup_zone,payment_type"
  YELLOW_CLUSTERING_COL: "PULocationID,VendorID,payment_type"
  YELLOW_PART_COL: "tpep_pickup_datetime"
  YELLOW_HIST_PART_COL: "first_day_of_month"