name: 'nytaxi'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  +persist_docs:
    relation: true
    columns: true
  elementary:
    +schema: "elementary"
    +enabled: true 



vars:
  'dbt_date:time_zone': 'UTC'
  'disable_dbt_artifacts_autoupload': 'true'
  dmt_mappings:
    test_suite_1:
      sources:
        staging_data:
          yellow_staging: test_dbt__ml__yellow_fare
    test_suite_2:
      sources:
        historical_data:
          yellow_historical: test_dbt__bi__yellow_m2m
tests:
  # +severity: warn
  +error_if: ">10000"
  +warn_if: ">1000"  # all tests
  +store_failures: true 

