apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - name: prometheus-port
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus