apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-exporter-secret
stringData:
  DATA_SOURCE_URI: "%!s(<nil>):5432/?sslmode=disable"
  DATA_SOURCE_USER: ${POSTGRES_USER}
  DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}