apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml_serve
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: ml_serve
  template:
    metadata:
      labels:
        app: ml_serve
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ml_serve
            topologyKey: kubernetes.io/hostname
      containers:
        - name: ml_serve
          image:  eu.gcr.io/{{ job.project }}/serving
          imagePullPolicy: Always
          ports:
            - name: serving-port
              containerPort: 8501
          env:
            - name: MLFLOW_URI
              value: "http://mlflow-service.default.svc.cluster.local:5000"
            - name: MLFLOW_EXPERIMENT_NAME
              value: "taxi-fare-prediction-v3"

      nodeSelector:
        cloud.google.com/gke-nodepool: "{{ job.nodeSelector }}"
        iam.gke.io/gke-metadata-server-enabled: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: serve-service
spec:
  type: NodePort
  ports:
    - name: serving-port
      port: 8501
      targetPort: 8501
  selector:
    app: ml_serve
