apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-serve
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: ml-serve
  template:
    metadata:
      labels:
        app: ml-serve
    spec:
      containers:
        - name: ml-serve
          image:  eu.gcr.io/stellarismusv2/serving
          imagePullPolicy: Always
          ports:
            - name: serving-port
              containerPort: 8501
      nodeSelector:
        cloud.google.com/gke-nodepool: base
        iam.gke.io/gke-metadata-server-enabled: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: serve-service
spec:
  type: NodePort
  ports:
    - name: serving-port
      port: 8501
      targetPort: 8501
  selector:
    app: ml-serve
