apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  annotations:
    reloader.stakater.com/match: "true"
stringData:
  aws_creds.json: |-
    {
        "accessKeyId": "$AWS_ACCESS_KEY_ID",
        "secretAccessKey": "$AWS_SECRET_ACCESS_KEY"
    }