apiVersion: v1
kind: ConfigMap
metadata:
  name: git-env
data:
  GIT_SYNC_REV: "HEAD"
  GIT_SYNC_BRANCH: "main"
  GIT_SYNC_REPO: "https://github.com/Liftingthedata/taxi-pls.git"
  GIT_SYNC_DEPTH: "1"
  GIT_SYNC_ROOT: "/git"
  GIT_SYNC_DEST: "repo"
  GIT_SYNC_USERNAME: "Liftingthedata"
  GIT_SYNC_WAIT: "5"
  GIT_SYNC_MAX_SYNC_FAILURES: "0"
  GIT_KNOWN_HOSTS: "false"
  GIT_SYNC_PASSWORD: "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"
