apiVersion: v1
kind: Service
metadata:
  name: ingress-load-balancer
  labels:
    app: ingress
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: ingress