apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  type: LoadBalancer
  selector:
    svc: external-lb
  ports:
    - name: flask-port
      port: 5000
      targetPort: 5000
    - name: grafana-port
      port: 3000
      targetPort: 3000
