apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-env
  annotations:
    reloader.stakater.com/match: "true"
data:
  # GCP INFRA
  GOOGLE_CLOUD_PROJECT: ${PROJECT}
  PROJECT: ${PROJECT}
  GCP_REGION: ${GCP_REGION}
  GCP_ZONE: ${GCP_ZONE}

  # Buckets
  STAGING_BUCKET: ${STAGING_BUCKET}
  SPARK_BUCKET: ${SPARK_BUCKET}
  AWS_DUMMY_BUCKET: ${AWS_DUMMY_BUCKET}
  DOCS_BUCKET: ${DOCS_BUCKET}
  CODE_BUCKET: ${CODE_BUCKET}
  MLFLOW_BUCKET: ${MLFLOW_BUCKET}
  # K8
  GKE_CLUSTER_NAME: ${GKE_CLUSTER_NAME}
  CLUSTER_SA: ${CLUSTER_SA}
  CLUSTER_KSA: ${CLUSTER_KSA}
  SPARK_JOBS_NODE_POOL: ${SPARK_JOBS_NODE_POOL}
  BASE_NODE_POOL: ${BASE_NODE_POOL}
  TRAINING_NODE_POOL: ${TRAINING_NODE_POOL}

  # DATASETS
  STAGING_DATASET: ${STAGING_DATASET}
  TRIAGE_DATASET: ${TRIAGE_DATASET}
  ML_DATASET: ${ML_DATASET}
  HISTORICAL_DATASET: ${HISTORICAL_DATASET}
  SEEDS_DATASET: ${SEEDS_DATASET}

  # Tables
  YELLOW_TRIAGE_TABLE: ${YELLOW_TRIAGE_TABLE}
  YELLOW_STAGING_TABLE: ${YELLOW_STAGING_TABLE}
  YELLOW_SUMMARY_TABLE: ${YELLOW_SUMMARY_TABLE}

  # AWS
  AWS_REGION: ${AWS_REGION}
  TARGET_S3_BUCKET: ${TARGET_S3_BUCKET}

  # Great Expectations
  GE_CONFIG_FILE_PATH: ${GE_CONFIG_FILE_PATH}
  CHECKPOINT_CONFIG_FILE_PATH: ${CHECKPOINT_CONFIG_FILE_PATH}
  ML_TRAINING_SIZE: "${ML_TRAINING_SIZE}"
  VALIDATION_THRESHOLD: "${VALIDATION_THRESHOLD}"
  FAIL_ON_VALIDATION_FAILURE: "${FAIL_ON_VALIDATION_FAILURE}"

