name: apps

on:
  push:
    branches:
    - main
    paths:
      - 'components/docs_app/docker/app.py'
      - 'components/data_validation/**'
      - 'components/kafka/scripts/**'
      - 'components/airflow/dags/**'
      - 'components/ml_train/script/**'
      - 'components/spark/scripts/**'
      - 'components/ml_serve/docker/*.py'
      - 'components/ml_train/scripts/**'
      - 'scripts/create_seed.py'
  pull_request:
    branches:
    - main
    paths:
      - 'components/docs_app/docker/app.py'
      - 'components/data_validation/**'
      - 'components/kafka/scripts/**'
      - 'components/airflow/dags/**'
      - 'components/ml_train/script/**'
      - 'components/spark/scripts/**'
      - 'components/ml_serve/docker/*.py'
      - 'components/ml_train/scripts/**'
      - 'scripts/create_seed.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      - name: Install poetry
        run: |
          python -m pip install poetry
      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Run tests [ s -> print statements ]
        run: |
          python -m poetry run python -m pytest -sxv
          # s for print statements
          # x to fail fast
          # v to increase verbosity
      - name: Lint
        run: python -m poetry run python -m pylint --recursive=y .
