name: CI


on:
  push:
    branches: [ "main" ]
    paths:
      - 'components/postgres/docker/**'
jobs:
  create_env_file:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV
      - run: |
          echo ${{ env.PROJECT }}
  # build-airflow-image:
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.event.head_commit.modified, 'airflow/docker/')
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build and push Airflow image
  #       uses: docker://gcr.io/kaniko-project/executor:v1.1.0
  #       with:
  #         args: >-
  #           --context=dir:///github/workspace/airflow/docker
  #           --destination=eu.gcr.io/<your-project-id>/airflow:latest
  #         dockerfile: airflow/docker/Dockerfile
  #         service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

  build-postgres-image:
    runs-on: ubuntu-latest
    # needs: create_env_file
    if: startsWith(github.event.head_commit.modified, 'components/postgres/docker/')
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Postgres image
        uses: docker://gcr.io/kaniko-project/executor:v1.1.0
        with:
          args: >-
            --context=dir:///github/workspace/postgres/docker
            --destination=eu.gcr.io/${{ env.PROJECT }}/postgres:latest
          dockerfile: postgres/docker/Dockerfile
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
