name: CI


on:
  push:
    branches: [ "main" ]
    paths:
      - 'components/*/docker/**'


jobs:
  checkchanges:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for comp in "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}  | grep -E "components/.+/docker" | awk -F '/' '{print $2}' | tr '[:lower:]' '[:upper:]')"; do
              echo "$comp=RUN" >> $GITHUB_ENV
          done
      - run: |
          echo ${{ env.AIRFLOW }}
  # create_env_file:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 'Create env file'
  #       run: |
  #         echo "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV
  #     - run: |
  #         for path in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}  | grep -E "components/.+/docker" | awk -F '/' '{print $2}' | tr '[:lower:]' '[:upper:]'); do
  #             echo "$path=RUN" >> $GITHUB_ENV
  #         done
  #     - run: |
  #         echo ${{ env.PROJECT }} && echo ${{ env.AIRFLOW }}
  # airflow-job:
  #   runs-on: ubuntu-latest
  #   needs: create_env_file
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Detect changed directories
  #     run: |
  #       for path in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}  | grep -E "components/.+/docker" | awk -F '/' '{print $2}'); do
  #         echo $path="RUN" >> $GITHUB_ENV
  #         echo $path
  #       done
  #       echo "${{ env.airflow }}"
    # - name: Build and push Airflow image
    #   uses: docker://gcr.io/kaniko-project/executor:v1.1.0
    #   if: contains(env.airflow, 'RUN')
    #   with:
    #     args: >-
    #       --context=dir:///github/workspace/components/airflow/docker
    #       --destination=eu.gcr.io/${{ env.PROJECT }}/airflow:${{ github.sha }}
    #     dockerfile: components/airflow/docker/Dockerfile
    #     service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
# jobs:
#   create_env_file:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 'Create env file'
#         run: |
#           echo "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV
#       - run: |
#           echo ${{ env.PROJECT }}
#   # build-airflow-image:
#   #   runs-on: ubuntu-latest
#   #   if: startsWith(github.event.head_commit.modified, 'airflow/docker/')
#   #   steps:
#   #     - uses: actions/checkout@v2
#   #     - name: Build and push Airflow image
#   #       uses: docker://gcr.io/kaniko-project/executor:v1.1.0
#   #       with:
#   #         args: >-
#   #           --context=dir:///github/workspace/airflow/docker
#   #           --destination=eu.gcr.io/<your-project-id>/airflow:latest
#   #         dockerfile: airflow/docker/Dockerfile
#   #         service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

#   build-postgres-image:
#     runs-on: ubuntu-latest
#     if: startsWith(github.event.head_commit.modified, 'components/postgres/docker/')
#     steps:
#       - uses: actions/checkout@v3
#       - name: Build and push Postgres image
#         uses: docker://gcr.io/kaniko-project/executor:v1.1.0
#         with:
#           args: >-
#             --context=dir:///github/workspace/postgres/docker
#             --destination=eu.gcr.io/${{ env.PROJECT }}/postgres:latest
#           dockerfile: postgres/docker/Dockerfile
#           service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

