name: CI


on:
  push:
    branches: [ "main" ]
    paths:
      - 'components/*/docker/**'


jobs:
  setup-envs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create env file and checks which components were modified'
        id: files
        uses: Ana06/get-changed-files@v2.2.0
      - run: |
          echo "${{ steps.files.outputs.all }}"  | xargs -n1 | grep -E "components/.+/docker" | awk -F '/' '{print $2}' | tr '[:lower:]' '[:upper:]' | while read c; do
              echo $c="RUN" >> $GITHUB_ENV
          done
          echo "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV
          echo WORKDIR="${{ github.workspace }}" >> $GITHUB_ENV
      - run: |
          echo ${{ env.PROJECT }} && echo ${{ env.AIRFLOW }}
          echo ${PWD}
          cat ${{ github.workspace }}/taxi-pls/components/airflow/docker/Dockerfile
      # - name: Build and push Airflow image
      #   uses: docker://gcr.io/kaniko-project/executor:v1.1.0
      #   if: contains(env.AIRFLOW, 'RUN')
      #   with:
      #     args: >-
      #       --context=dir://${{ env.WORKDIR }}/components/airflow/docker
      #       --destination=eu.gcr.io/${{ env.PROJECT }}/airflow:${{ github.sha }}
      #       --dockerfile=Dockerfile
      #     service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      # - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
      #   with:
      #     gcloud_service_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      #     registry: eu.gcr.io
      #     project_id: ${{ env.PROJECT }}
      #     image_name: airflow
      #     image_tag: latest,v1
      #     dockerfile: /home/runner/work/taxi-pls/taxi-pls/components/airflow/docker/Dockerfile
      #     context: /home/runner/work/taxi-pls/taxi-pls/components/airflow/docker
# jobs:
#   create_env_file:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 'Create env file'
#         run: |
#           echo "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV
#       - run: |
#           echo ${{ env.PROJECT }}
#   # build-airflow-image:
#   #   runs-on: ubuntu-latest
#   #   if: startsWith(github.event.head_commit.modified, 'airflow/docker/')
#   #   steps:
#   #     - uses: actions/checkout@v2
#   #     - name: Build and push Airflow image
#   #       uses: docker://gcr.io/kaniko-project/executor:v1.1.0
#   #       with:
#   #         args: >-
#   #           --context=dir:///github/workspace/airflow/docker
#   #           --destination=eu.gcr.io/<your-project-id>/airflow:latest
#   #         dockerfile: airflow/docker/Dockerfile
#   #         service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

#   build-postgres-image:
#     runs-on: ubuntu-latest
#     if: startsWith(github.event.head_commit.modified, 'components/postgres/docker/')
#     steps:
#       - uses: actions/checkout@v3
#       - name: Build and push Postgres image
#         uses: docker://gcr.io/kaniko-project/executor:v1.1.0
#         with:
#           args: >-
#             --context=dir:///github/workspace/postgres/docker
#             --destination=eu.gcr.io/${{ env.PROJECT }}/postgres:latest
#           dockerfile: postgres/docker/Dockerfile
#           service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

