name: Components-CD


on:
  push:
    branches: [ "main" ]
    paths:
      - 'components/*/docker/**'


jobs:
  setup-envs:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     component: ["AIRFLOW", "POSTGRES", "MLFLOW"]
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - run: |
          echo "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV
      - id: files
        uses: Ana06/get-changed-files@v2.2.0
      - run: |
          echo "${{ steps.files.outputs.all }}"  | xargs -n1 | grep -E "components/.+/docker" | awk -F '/' '{print $2}' | tr '[:lower:]' '[:upper:]' | while read c; do
              echo $c="RUN" >> $GITHUB_ENV
          done
      - name: Run script file
        run: |
          chmod +x ${{ github.workspace }}/scripts/docker.sh
          .${{ github.workspace }}/scripts/docker.sh
        shell: bash
      # - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
      #   if: contains(matrix.component, 'RUN')
      #   with:
      #     gcloud_service_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      #     registry: eu.gcr.io
      #     project_id: ${{ env.PROJECT }}
      #     image_name: airflow
      #     image_tag: latest,v1 #${{ github.sha }}
      #     dockerfile: ${{ github.workspace }}/components/${{ matrix.component }}/docker/Dockerfile
      #     context: ${{ github.workspace }}/components/${{ matrix.component }}/docker
      # - name: kubectl - Google Cloud GKE cluster.
      #   if: contains(matrix.component, 'RUN')
      #   uses: ameydev/gke-kubectl-action@master
      #   env:
      #     PROJECT_ID: ${{ env.PROJECT }}
      #     APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      #     CLUSTER_NAME: ${{ env.GKE_CLUSTER_NAME }}
      #     ZONE_NAME: ${{ env.GCP_ZONE }}
      #   with:
      #     args: rollout restart deployment ${{ matrix.component }}
# jobs:
#   create_env_file:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 'Create env file'
#         run: |
#           echo "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV
#       - run: |
#           echo ${{ env.PROJECT }}


#   build-postgres-image:
#     runs-on: ubuntu-latest
#     if: startsWith(github.event.head_commit.modified, 'components/postgres/docker/')
#     steps:
#       - uses: actions/checkout@v3
#       - name: Build and push Postgres image
#         uses: docker://gcr.io/kaniko-project/executor:v1.1.0
#         with:
#           args: >-
#             --context=dir:///github/workspace/postgres/docker
#             --destination=eu.gcr.io/${{ env.PROJECT }}/postgres:latest
#           dockerfile: postgres/docker/Dockerfile
#           service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

