name: docker-images-cicd
on:
  push:
    branches: [ "main" ]
    paths:
      - 'components/*/manifests/**'

jobs:
  apply-k8s-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - run: |
          echo "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV
      - id: files
        uses: Ana06/get-changed-files@v2.2.0
      - run: |
          echo CHANGED_COMPONENTS=$(echo "${{ steps.files.outputs.all }}"  | xargs -n1 | grep -E "components/.+/docker") >> $GITHUB_ENV
          echo ${{ env.CHANGED_COMPONENTS }}
      # - name: Run script file
      #   working-directory: .
      #   run: |
      #     chmod +x scripts/docker.sh
      #     ./scripts/docker.sh
      #   shell: bash
