name: PySparkApps Tests

on:
  push:
    branches:
    - main
    paths:
      - 'components/spark/scripts/**'

  pull_request:
    branches:
    - main
    paths:
      - 'components/spark/scripts/**'


jobs:
  test_pysapps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - run: |
          echo -n "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install --dev --verbose
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.1.1'
      - name: Add Spark Home
        run: |
          sed -i '/spark_home = \/opt\/spark/d' pytest.ini
      - name: Run tests
        run: |
          # export PYTHONPATH=$PYTHONPATH:.
          pipenv run python -m pytest tests/test_spark_fns.py -svx --trace
          # # s for print statements
          # # v to increase verbosity
      - name: Format-Lint-Sort
        run: |
          if [[ $(git diff-tree --no-commit-id --name-only --diff-filter=ACMRT -r ${{ github.sha }} -- '*.py' | xargs) ]]; then
          pipenv run python -m black --check $(git diff-tree --no-commit-id --name-only --diff-filter=ACMRT -r "$GITHUB_SHA" -- '*.py' | xargs)
          pipenv run python -m isort $(git diff-tree --no-commit-id --name-only --diff-filter=ACMRT -r "$GITHUB_SHA" -- '*.py' | xargs)
          pipenv run python -m pylint $(git diff-tree --no-commit-id --name-only --diff-filter=ACMRT -r "$GITHUB_SHA" -- '*.py' | xargs)
          fi
